name: Build and Push Docker Image

on:
  push:
    branches:
      - "**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase repo owner and repo name
        id: vars
        run: |
          echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
          echo "repo_name=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sanitize branch name
        id: sanitize
        run: |
          sanitized=$(echo "${GITHUB_REF_NAME}" | sed 's/[^a-zA-Z0-9._-]/-/g')
          echo "sanitized_ref=$sanitized" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (branch tag only)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ steps.vars.outputs.repo_name }}:${{ steps.sanitize.outputs.sanitized_ref }}

      - name: Also push :latest tag (only on main or master)
        if: github.ref_name == 'main' || github.ref_name == 'master'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.owner_lc }}/${{ steps.vars.outputs.repo_name }}:latest
